name: "ЁЯРЫ ржмрж╛ржЧ рж░рж┐ржкрзЛрж░рзНржЯ"
description: "ржПржХржЯрж┐ рж╕ржорж╕рзНржпрж╛/рждрзНрж░рзБржЯрж┐ рж░рж┐ржкрзЛрж░рзНржЯ ржХрж░рзБржи"
title: "[Bug] "
labels: ["bug"]
body:
  - type: dropdown
    attributes:
      label: "ЁЯУж ржбрзЗржкрзНрж▓ржпрж╝ржорзЗржирзНржЯ ржкржжрзНржзрждрж┐"
      multiple: true
      options:
        - "ржЕржлрж┐рж╕рж┐ржпрж╝рж╛рж▓ ржЗржирж╕рзНржЯрж▓ ржкрзНржпрж╛ржХрзЗржЬ"
        - "Vercel"
        - "Zeabur"
        - "Sealos"
        - "Netlify"
        - "Docker"
        - "ржЕржирзНржпрж╛ржирзНржп"
    validations:
      required: true
  - type: input
    attributes:
      label: "ЁЯУМ рж╕ржлржЯржУржпрж╝рзНржпрж╛рж░ рж╕ржВрж╕рзНржХрж░ржг"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: "ЁЯТ╗ ржЕржкрж╛рж░рзЗржЯрж┐ржВ рж╕рж┐рж╕рзНржЯрзЗржо"
      multiple: true
      options:
        - "Windows"
        - "macOS"
        - "Ubuntu"
        - "ржЕржирзНржпрж╛ржирзНржп рж▓рж┐ржирж╛ржХрзНрж╕"
        - "iOS"
        - "iPad OS"
        - "Android"
        - "ржЕржирзНржпрж╛ржирзНржп"
    validations:
      required: true
  - type: input
    attributes:
      label: "ЁЯУМ рж╕рж┐рж╕рзНржЯрзЗржо рж╕ржВрж╕рзНржХрж░ржг"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "ЁЯМР ржмрзНрж░рж╛ржЙржЬрж╛рж░"
      multiple: true
      options:
        - "Chrome"
        - "Edge"
        - "Safari"
        - "Firefox"
        - "ржЕржирзНржпрж╛ржирзНржп"
    validations:
      required: true
  - type: input
    attributes:
      label: "ЁЯУМ ржмрзНрж░рж╛ржЙржЬрж╛рж░ рж╕ржВрж╕рзНржХрж░ржг"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "ЁЯРЫ рж╕ржорж╕рзНржпрж╛ ржмрж░рзНржгржирж╛"
      description: ржПржХржЯрж┐ рж╕рзНржкрж╖рзНржЯ ржПржмржВ рж╕ржВржХрзНрж╖рж┐ржкрзНржд рж╕ржорж╕рзНржпрж╛ ржмрж░рзНржгржирж╛ ржкрзНрж░ржжрж╛ржи ржХрж░рзБржи, ржпржжрж┐ ржЙржкрж░рзЗрж░ ржмрж┐ржХрж▓рзНржкржЯрж┐ `ржЕржирзНржпрж╛ржирзНржп` рж╣ржпрж╝, рждржмрзЗ ржмрж┐рж╕рзНрждрж╛рж░рж┐рждржнрж╛ржмрзЗ ржмрзНржпрж╛ржЦрзНржпрж╛ ржХрж░рзБржиред
    validations:
      required: true
  - type: textarea
    attributes:
      label: "ЁЯУ╖ ржкрзБржирж░рзБрждрзНржкрж╛ржжржи ржкржжржХрзНрж╖рзЗржк"
      description: ржПржХржЯрж┐ рж╕рзНржкрж╖рзНржЯ ржПржмржВ рж╕ржВржХрзНрж╖рж┐ржкрзНржд ржмрж░рзНржгржирж╛ ржкрзНрж░ржжрж╛ржи ржХрж░рзБржи, ржХрж┐ржнрж╛ржмрзЗ рж╕ржорж╕рзНржпрж╛ржЯрж┐ ржкрзБржирж░рзБрждрзНржкрж╛ржжржи ржХрж░ржмрзЗржи рждрж╛ ржмрзНржпрж╛ржЦрзНржпрж╛ ржХрж░рзБржиред
  - type: textarea
    attributes:
      label: "ЁЯЪж ржкрзНрж░рждрзНржпрж╛рж╢рж┐ржд ржлрж▓рж╛ржлрж▓"
      description: ржПржХржЯрж┐ рж╕рзНржкрж╖рзНржЯ ржПржмржВ рж╕ржВржХрзНрж╖рж┐ржкрзНржд ржмрж░рзНржгржирж╛ ржкрзНрж░ржжрж╛ржи ржХрж░рзБржи, ржЖржкржирж┐ ржХрж┐ ржЖрж╢рж╛ ржХрж░рзЗржЫрж┐рж▓рзЗржи рждрж╛ ржмрзНржпрж╛ржЦрзНржпрж╛ ржХрж░рзБржиред
  - type: textarea
    attributes:
      label: "ЁЯУЭ ржЕрждрж┐рж░рж┐ржХрзНржд рждржерзНржп"
      description: ржпржжрж┐ ржЖржкржирж╛рж░ рж╕ржорж╕рзНржпрж╛рж░ ржЬржирзНржп ржЖрж░ржУ ржмрзНржпрж╛ржЦрзНржпрж╛рж░ ржкрзНрж░ржпрж╝рзЛржЬржи рж╣ржпрж╝ ржмрж╛ ржЖржкржирж╛рж░ рж╕ржорж╕рзНржпрж╛ржЯрж┐ ржПржХржЯрж┐ рж╕рж╛ржзрж╛рж░ржг ржЙржжрж╛рж╣рж░ржгрзЗ ржкрзБржирж░рзБрждрзНржкрж╛ржжржи ржХрж░рж╛ ржирж╛ ржпрж╛ржпрж╝, рждржмрзЗ ржПржЦрж╛ржирзЗ ржЖрж░ржУ рждржерзНржп ржпрзЛржЧ ржХрж░рзБржиред
